language: node_js
node_js:
  - "10"
script:
  - npm i
  - npm run test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_349a92424679_key -iv $encrypted_349a92424679_iv
    -in deploy_rsa-front.enc -out deploy_rsa-front -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa-front
  - ssh-add /tmp/deploy_rsa-front
  - git remote set-url origin https://Sehsyha:$GITHUB_API_KEY@github.com/Sehsyha/crounch-front.git
  - make bump-version
  - make build-image
  - export VERSION_NUMBER=$(jq -r ".version" package.json)
  - make build-image
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push $DOCKER_USER/crounch-front:$VERSION_NUMBER
deploy:
  provider: script
  script: ssh -oStrictHostKeyChecking=no -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/front.sh $VERSION_NUMBER
  on:
    branch: master
env:
  global:
    - secure: aMysjxzaYXWiOsukwK7r8Dck34of5cE52B/YaZLH29gpXas5UsKJ4zguM9wLmM+/gFianVCzpo+LLcE3XSjzg45tJ7BJJmsrQphOkBUfV1W9oQ3PBTOIsn4K7o94XZL5TGzfZ4fJXYDAI7Vaz9Wr9gto9kCDJ9PaaprZ00cIpb5pnOl2Ftc6n3RbQ2YlGnObNK6JpP01lwcoax7EIPC+QSB4Ygm6u/EsiNohisRSmngFWs4yNWl1q9/3uGJ1kSl3NuAGVObUAgt74ChIBIMAR0JYWPBwb5x+tUxbOqfunRE8Fvwf5N6DFaR7y8qsW0H8Po6fI7+eu6B8+qLHVU09a1yWth79hP2REOkRX5ai6INlOh5P5hmYxFg7E6aWg6vfYuFD5gmz+q/wWUEzqEuxgiGtnNBbTA8x9qxvky/0ozO9eElrdma4bBASaonjxzU5j4NeEzXyU+67JlFS6n6pAQwuZk28UWG+IHDlUnnGrmAwsfcm91WJB1vFxJ170dD5draA0G+3+D9bhP0Ca5G1HtT8HMBMQycBpyGQ5L39ve+bSmbyqXslohgWkuCsOpAYR5mAa29WHrSU8rTSfkps5UaO5fzR1z0puynMAPrSodPjNIgeXjS/UbaGINPkuFLOvAnqKxLEVxxK9vbaSD6uLdPX1j8OBRfVyQ/7u2k87EA=
    - secure: UvdidRDcHK5xrP3ewm3Fr0UzahKBHz0vq4CLZwKRWTHeKjQqvHRp1PYgGIKluys2RsPoNz/o/RHfkFmYUE/IkI4KXMYtHf6QgZWAL3z1p26/tgn+Z5HHyIIoJ1KfWWpZMPNiwvjB43n6UH6mCmcHm4QfRWvZbhdcjA/dD4zAKaCqUWhwOT0eiNitudH23mJtYb7WDzKAG8dQQjgfLYaiHUZNRh8fVwH5KVeN/fJIBEU90gSx4gHn4mhyBmRiGzN8ntLroTcbQfnLWQaAlBelF7zty9L9TbKcEEhlcsGgeVeLej5iNQWgFr4SYmAH/VrOhltPCnXIr/wopxkI7djGMJI+W57FQz/FcY8W0lmhytYaZF1HfyRX2B30Jqz7wPaKkaYFtBqacc9+uqKxrZNZSqPrRHIUNKSb/2WjsnQs3/D8iEaKsJhJMUcYoVHwLKZWxbgAkKTrP/HW0RNYNIkNhedLa++DC83CVxq3DZAxqNZ5caQjDJdpkO0bt6t/hKDgFbcN0H0k0qk7Yv//IajPpLtgMgzWWdwY0/IOcyHzgrUgao5uZkXUYudMmOmeF2vb6ecaopReyvIk+tHQZTC+q6Y5Z/UzGr9PdyF1ze3i6lRcG4DbhlpnjO8XDHS1VlSIIBmA6zZ5v0mzpP9N7Ln3h3cFe1O3F25f6705RezUyZ8=
    - secure: THMkFSR+hE10vk+yuxI4QFEtTSGFSUcRBChescySO91wKGI9+hQkpTSnVKgg8DODkWNiZrBs+3FZ9C+BeP18oex4cTRBOoe35Hm00XEa4M1+VZ/1aIUNFbruNG29tRTQR2KLDBMCiaa3/dfuiaFHCe33DlqGbswlOatO+C04qfgtTwHazotTu4S/pclxL+7WN2zIim19uz8AuDy9K2G6d/ct23L0h+i3M2kdGT4LM5aNYKa6C23oJ9snseKY9iU7Sdz7jLWosUdONWpoNgLgcpnKZ6viT6IXIbFXOGpd5n4xKS6MkVEjQs5Ri4y2sWVK4DsL8CBSnfks4TqXTbdVkivakUvdsDRzbytwYgVg+48wP23bzkkJFM8oVf5n1RtN7etSp9fomxJtPtqZJCzI9mnESOdAAheJ4X07+JyrkxxZYnxUpeakgVhLJEOOzyUi6uKNYitA3517rmv55OAtyTsCIgDV+7dxTZH6maCwyKlTPsOE0uKNYaZZYjirQYTpg6NaQmLNV57asZD+K7DKd7txm2TX1zhesW05WnJ+EVmSV9VNwmX7/xC2FxoXer1Yd8OVsVt4Ssc4hqHrrHFdDF+2n0H9aebTCECoQWdMzO51WitDoXGYy6bfdaXsgQYs819c2trk9BeVA0sWuaALABbIYxzoMzogORbACLO6m/c=
    - secure: j92co1TU4LOB6+VUFbWMt5zSwvPQlG9KJ5jRDAVHQU0KAfkRKjO1Sl1NIUuIcEbrgGt17BF2mpU8NQlSjz0/U/HqV9iHbFadcRcXuauHTUw9ouMLOM1A0t2rXuCZwnVNZlzk/GTwPCENpd/L9VoBIzuDeI/66WtqJsoJ+2xlWVOxLqD+JKC6dx62Zt/jmrDHCzQzaDJLjzHGrc96dNBpXUo2uDxtk0WT5Iliz6X7rHso28686onZTZeh8ijnGPsUG3TThToLmH9qcBsarZ6sJkwkNynFWoJHeN2Y0q6ru3aDZxM3RbVhBca4jM6imjUp9JRaHqe7RMPooYI9oLU9h47P3cs93HNVl3c0fF2ZYt5f3hIpMlsaS9UIkEwL8qcCOxB2YK5PvPVUXD+FduRJjtaVv4aGQBJbJLf8c0gDZeysajVr0+NQaXtg5zGnl5CadRS2L/pn/herz8J99CAs8k6RjKcsuojsJ1yDsOgjgHi94kn6lPK7VCfTLOPZsPIgK8ERRXWJxTlMCh3J5AHQEx9C5PK5Eui+hXvwdrqul8dl+d1yRG9GdmLSXtGqQKzQEC64LwvkEi7Ub8kDUIsMypx5QzBfGi6M+2Xwhi1XhFsSBX0lyGfq5vB1fCiggFzxAGn0yjeFhPWkromcwTvlqFfIWy5UavuN99Cmtnone2I=
