version: "2.1"

services:
  wait:
    image: alpine
    depends_on:
      crounch-back:
        condition: service_healthy
      crounch-front:
        condition: service_healthy
  crounch-back:
    image: "sehsyha/crounch-back"
    ports:
      - "3000:3000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O /dev/null http://localhost:3000/health || exit 1",
        ]
      interval: 10s
      timeout: 30s
      retries: 6
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 3
  crounch-front:
    build:
      context: ../
      dockerfile: containers/Dockerfile
    volumes:
      - ./nginx_acceptance.conf:/etc/nginx/conf.d/acceptance.conf
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 6
