name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    - name: Install dependencies
      run: npm ci
      
    - name: Lint
      run: npm run lint

    - name: Unit tests
      run: npm run test:ci
    
#    - name: Mutation tests
#      run: npm run test:mutation
#    - name: Bump version
#      run: make bump-version
    
    - name: Build image
      run: make build-image
    
#    - name: Publish image
#      run: make publish-image
