name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    - name: Install dependencies
      run: npm ci
    
    - name: Save build
      uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: .

  quality:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Get build
        uses: actions/download-artifact@v1
        with:
          name: build-artifacts
      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test:ci
    
#    - name: Mutation tests
#      run: npm run test:mutation
